In [1]:
import numpy as np 

In [5]:
a = np.zeros((3, 4))

In [6]:
print(a.shape)
print(a.size)
print(a.ndim)

(3, 4)
12
2


In [7]:
np.full((3, 4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [10]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.linspace(0, 5/3, 6)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667])

In [ ]:
np.random.rand(2, 3) # uniform distribution

array([[0.24661987, 0.39373372, 0.08740042],
       [0.22423007, 0.25100511, 0.77420965]])

In [ ]:
np.random.randn(2, 3) # normal/ gaussian distribution

array([[-0.22511473, -1.69978684, -0.92501178],
       [-1.28099773,  2.41564614, -0.29142883]])

In [15]:
a.dtype 

dtype('float64')

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
print(a.size)
print(a.itemsize) # size in bytes for each item 

12
8


In [19]:
a = np.arange(24)
a 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
a.shape = (2, 12) # change in place 
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
a2 = a.reshape(4,6) # create a new np array pointing at the *same* data 
a2 

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [23]:
a2[1,2] = 99
print(a2)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7 99  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5  6  7 99  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]


In [ ]:
a3 = a2.ravel() # return a 1d array also pointing to the same data 

In [25]:
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7, 99,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([5, 6, 7])
print(a - b) # apply element wise operations 
print(a / b)
print(a * b) # not matrix multiplication 

[-4 -4 -4]
[0.2        0.33333333 0.42857143]
[ 5 12 21]


- broadcasting 
- rule 1: numpy compares the shapes of the two arrays from right to left, if two dims aren't the same: if any is 1, it's fine, otherwise, it's a value error

In [27]:
h = np.arange(5).reshape((1, 1, 5))
h

array([[[0, 1, 2, 3, 4]]])

In [28]:
h + [1, 2, 3, 4, 5]

array([[[1, 3, 5, 7, 9]]])

- rule 2: if the operation is compatible and an array has 1 along a dimension, then the final dimension is the max of both curr dims, and the value at dim 1 is repated along that axis 

In [30]:
k = np.arange(6).reshape(2, 3)
k

array([[0, 1, 2],
       [3, 4, 5]])

In [31]:
k + [[100], [200]] # (2, 3) + (2 * 1) = (2, 3)

array([[100, 101, 102],
       [203, 204, 205]])

In [32]:
k + [100, 200, 300] # (2, 3) + (3,)

array([[100, 201, 302],
       [103, 204, 305]])

In [33]:
k + 1000

array([[1000, 1001, 1002],
       [1003, 1004, 1005]])